---
galaxy_info:
  author: Fouad Semaan
  description: 'Installs kubernetes binaries to /usr/local/bin'
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  
  galaxy_tags:
    - kubernetes

dependencies:
  - role: andrewrothstein.unarchive-deps
    version: v1.0.6
