---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/opt/kibana/config/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: configure default kibana index
  shell: |
    curl -s -XPUT {{ kibana_elasticsearch_url }}/.kibana/index-pattern/filebeat-* -d '{"title" : "filebeat-*",  "timeFieldName": "@timestamp"}'
    IDS=$(curl -s {{ kibana_elasticsearch_url }}/.kibana/config/_search?pretty=true | awk -F '"' '/_id/ { print $4  }')
    for i in $IDS; do
      curl -s -XPUT {{ kibana_elasticsearch_url }}/.kibana/config/$i -d '{"defaultIndex" : "filebeat-*"}'
    done
  register: kibana_index
  failed_when: "'\"failed\":0' not in kibana_index.stdout or kibana_index.stderr != '' or kibana_index.rc != 0"
