- hosts: kubernetes-master
  roles:
    - general
    - kubernetes
    - kubernetes-master
  environment:
    KUBECONFIG: /home/deploy/admin.conf

- hosts: kubernetes-nodes
  roles:
    - general
    - kubernetes
    - kubernetes-node
  environment:
    KUBECONFIG: /home/deploy/admin.conf
