- hosts: all
  roles:
    - { role: general, tags: general }
  tags:
    - general

- hosts: tls-server
  vars:
    TLS_DEST_BASENAME: 'taskmngr1'
    TLS_CREATE_SELFSIGNED: true
  roles:
    - { role: cdosborn.tls-cert, tags: tls-server }
  tags:
    - tls-server

- hosts: tls-client
  vars:
    TLS_DEST_BASENAME: 'taskmngr1'
    TLS_PRIVKEY_SRC_FILE: "files/{{ TLS_DEST_BASENAME }}.key"
    TLS_CERT_SRC_FILE: "files/{{ TLS_DEST_BASENAME }}.crt"
    TLS_CACHAIN_SRC_FILE: "files/{{ TLS_DEST_BASENAME }}.cachain.crt"
    # TLS_PRIVKEY_DEST_DIR_2: "/keys"
    TLS_CERT_DEST_DIR_2: "/etc/pki/ca-trust/source/anchors"
  roles:
    - { role: cdosborn.tls-cert, tags: tls-client }
  tags:
    - tls-client

- hosts: docker-registry
  vars:
    docker_install_compose: false
  roles:
    - { role: geerlingguy.docker, tags: docker }
    - { role: nephelaiio.docker-registry, tags: docker-registry }
  tags:
    - docker-registry

- hosts: kubernetes-master
  roles:
    - { role: geerlingguy.docker, tags: docker }
    - { role: kubernetes, tags: kubernetes }
    - { role: kubernetes-master, tags: kubernetes-master }
  vars:
    docker_install_compose: false
  environment:
    KUBECONFIG: /home/deploy/admin.conf
  tags:
    - kubernetes-master

- hosts: kubernetes-node
  roles:
    - { role: geerlingguy.docker, tags: docker }
    - { role: kubernetes, tags: kubernetes }
    - { role: kubernetes-node, tags: kubernetes-node }
  vars:
    docker_install_compose: false
  environment:
    KUBECONFIG: /home/deploy/admin.conf
  tags:
    - kubernetes-node

- hosts: jenkins-master
  vars:
    jenkins_hostname: taskmngr1
    jenkins_repo_url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    jenkins_repo_key_url: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
    java_version: 8
    # public_hostname: 'taskmngr1'
    # nexus_admin_password: 'admin'
    # nexus_timezone: 'Europe/Moscow'
    # apache_create_vhosts: no
    # httpd_server_name: 'taskmngr1'
    # httpd_setup_enable: true
  roles:
    - { role: williamyeh.oracle-java, tags: java }
    - { role: geerlingguy.jenkins, tags: jenkins-master }
    # - { role: savoirfairelinux.nexus3-oss, tags: nexus }
    # - { role: geerlingguy.apache, tags: apache }
  tags:
    - jenkins-master
