- hosts:  kubernetes-master
  tasks:
    - debug: msg="doesn't matter what you do, just that they were talked to previously."

- hosts: kubernetes-master
  roles:
    - general
    - kubernetes
    - kubernetes-master

- hosts: kubernetes-nodes
  roles:
    - general
    - kubernetes
    - kubernetes-node
