- hosts: kubernetes-master
  roles:
    - { role: general, tags: general }
    - { role: kubernetes, tags: kubernetes }
    - { role: kubernetes-master, tags: kubernetes-master }
  environment:
    KUBECONFIG: /home/deploy/admin.conf
  tags:
    - kubernetes-master

- hosts: kubernetes-nodes
  roles:
    - { role: general, tags: general }
    - { role: kubernetes, tags: kubernetes }
    - { role: kubernetes-node, tags: kubernetes-node }
  environment:
    KUBECONFIG: /home/deploy/admin.conf
  tags:
    - kubernetes-node

- hosts: jenkins-master
  vars:
    jenkins_hostname: taskmngr1
    jenkins_repo_url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    jenkins_repo_key_url: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
    java_version: 8
    # public_hostname: 'taskmngr1'
    # nexus_admin_password: 'admin'
    # nexus_timezone: 'Europe/Moscow'
    # apache_create_vhosts: no 
    # httpd_server_name: 'taskmngr1'
    # httpd_setup_enable: true
  roles:
    - { role: williamyeh.oracle-java, tags: java }
    - { role: geerlingguy.jenkins, tags: jenkins-master }
    # - { role: savoirfairelinux.nexus3-oss, tags: nexus }
    # - { role: geerlingguy.apache, tags: apache }
  tags:
    - jenkins-master
