---

- name: get public ssh key
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    key: "{{ lookup('file', '/home/' + ansible_local_user|quote + '/.ssh/id_rsa.pub') }}"

- name: permit sudo without password for deploy user
  lineinfile:
    dest: "/etc/sudoers.d/{{ ansible_ssh_user }}"
    create: yes
    state: present
    line: "{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: true
  become_method: sudo

- fail:

- name: disable password authentication via ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  become: true
  notify: restart ssh

- name: disable authentication as root
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  become: true
  notify: restart ssh

- name: remove password for deploy user
  shell: passwd -d "{{ ansible_ssh_user }}"
  become: true
