---

- include: get-cert-cn.yml
  when: TLS_DEST_BASENAME is undefined

# - name: make sure custom dirs for certs and keys exist
#   file:
#     path: "{{ item }}"
#     state: directory
#   with_items:
#     - "{{ TLS_PRIVKEY_DEST_DIR_2 }}"
#     - "{{ TLS_CERT_DEST_DIR_2 }}"

- name: Certificate files copied to target
  tags: [certs-copied]
  copy:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
  with_items:
    # - src_path: "{{ TLS_PRIVKEY_SRC_FILE }}"
    #   dest_path: "{{ TLS_PRIVKEY_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.key"
    # - src_path: "{{ TLS_CERT_SRC_FILE }}"
    #   dest_path: "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.crt"
    # - src_path: "{{ TLS_CACHAIN_SRC_FILE }}"
    #   dest_path: "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.cachain.crt"
    # - src_path: "{{ TLS_PRIVKEY_SRC_FILE }}"
    #   dest_path: "{{ TLS_PRIVKEY_DEST_DIR_2 }}/{{ TLS_DEST_BASENAME }}.key"
    - src_path: "{{ TLS_CERT_SRC_FILE }}"
      dest_path: "{{ TLS_CERT_DEST_DIR_2 }}/{{ TLS_DEST_BASENAME }}.crt"
    # - src_path: "{{ TLS_CACHAIN_SRC_FILE }}"
    #   dest_path: "{{ TLS_CERT_DEST_DIR_2 }}/{{ TLS_DEST_BASENAME }}.cachain.crt"
  register: certs_copied

- name: update client certificates bundle
  shell: "update-ca-trust extract"
  when: certs_copied.changed

- name: restart docker
  service:
    name: docker
    state: restarted
  ignore_errors: true
  when: certs_copied.changed

# - name: Full certificate chain created
#   shell: >
#     cat {{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.crt
#     {{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.cachain.crt >
#     {{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.fullchain.crt
