---

- name: TLS_DEST_BASENAME set to "selfsigned" if not already overridden
  set_fact:
    TLS_DEST_BASENAME: selfsigned
  when: TLS_DEST_BASENAME is undefined

- name: enable subjectAltName request on cert creating
  lineinfile:
    dest: "/etc/pki/tls/openssl.cnf"
    regexp: "^x509_extensions"
    line: "x509_extensions = v3_ca"
    insertafter: '^.* req .*$'

- name: set subjectAltName in openssl config (to get correct certs)
  lineinfile:
    dest: "/etc/pki/tls/openssl.cnf"
    regexp: "^subjectAltName"
    line: "subjectAltName=DNS:{{ tls_subjectAltNames[0] }}, DNS:{{ tls_subjectAltNames[1] }}"
    insertafter: '^.* v3_ca .*$'

- name: check if cert is already exists
  stat:
    path: "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.crt"
  register: cert_file

- name: Self-signed certificate and private key created
  tags: [selfsigned-cert-created]
  command: 'openssl req -newkey rsa:2048 -sha256 -x509 -nodes -new -days 3650 -subj "/CN={{ TLS_DEST_BASENAME }}" -keyout {{ TLS_PRIVKEY_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.key -out {{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.crt'
  when: (not cert_file.stat.exists) or (force_create_cert)

- name: Restricted file permissions set on private key
  when: ansible_distribution == "CentOS"
  file:
    path: "{{ item }}"
    owner: root
    mode: 0600
  with_items:
    - "{{ TLS_PRIVKEY_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.key"

- name: Empty CA chain file created
  tags: [selfsigned-empty-bundle-created]
  file:
    path: "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.cachain.crt"
    state: touch
  # The following two lines work around https://github.com/ansible/ansible-modules-core/issues/170
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: Full certificate chain (same as bare self-signed certificate) created
  tags: [selfsigned-fullchain-created]
  copy:
    src: "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.crt"
    dest: "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.fullchain.crt"
    remote_src: true

- name: copy certs and keys to ansible server
  fetch:
    src: "{{ item }}"
    dest: files/
    flat: yes
  with_items:
    - "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.crt"
    - "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.fullchain.crt"
    - "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.cachain.crt"
    - "{{ TLS_PRIVKEY_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.key"
