---

- name: Distro-specific variables gathered
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Ensure distro default cert paths exist
  tags: [ensure-distro-cert-paths]
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ TLS_PRIVKEY_DEST_DIR }}"
    - "{{ TLS_CERT_DEST_DIR }}"

- include: deploy-selfsigned.yml
  when: >
      TLS_CREATE_SELFSIGNED or
      TLS_PRIVKEY_SRC_FILE is undefined or
      TLS_CERT_SRC_FILE is undefined or
      TLS_CACHAIN_SRC_FILE is undefined

- include: deploy-provided.yml
  when: >
      not TLS_CREATE_SELFSIGNED and
      TLS_PRIVKEY_SRC_FILE is defined and
      TLS_CERT_SRC_FILE is defined and
      TLS_CACHAIN_SRC_FILE is defined

