---

- name: disable swap for session (required for kube)
  shell: "swapoff -a"
  changed_when: false
  when: disable_swap == true
  tags: ['swap']

- name: disable swap permanently (required for kube)
  lineinfile:
    dest: /etc/fstab
    regexp: '^([^#]* swap .*)'
    line: '# \1'
    backrefs: yes
    state: present
  when: disable_swap == true
  tags: ['swap']

- name: install iptables management utils
  yum:
    name: iptables-services
    state: latest

- name: deploy kubernetes.repo template to add kube repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: install kube base packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ kubelet_package_name }}"
    - "{{ kubeadm_package_name }}"
    - "{{ kubectl_package_name }}"
    - "{{ kubecni_package_name }}"

- name: change default kubelet cgroup driver to match docker's one
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '--cgroup-driver=systemd'
    replace: '--cgroup-driver=cgroupfs'

- name: update cgroup driver configuration for kubelet
  systemd:
    name: kubelet
    state: started
    daemon_reload: yes

- name: enable kube services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ kube_base_binaries }}"

- name: enable bridge-nf-iptables via sysctl (required for kubeadm)
  shell: "sysctl net.bridge.bridge-nf-call-iptables=1"
  changed_when: false

- name: enable bridge-nf-iptables autostart (req for kubeadm)
  lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: '^net.bridge.bridge-nf-call-iptables'
    line: "net.bridge.bridge-nf-call-iptables = 1"
