---

- name: install iptables management utils
  yum:
    name: iptables-services
    state: latest
  become: true

- name: deploy kubernetes.repo template to add kube repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644
  become: true

- name: install kube base packages
  yum:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ kube_base_packages }}"

- name: enable kube services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  become: true
  with_items: "{{ kube_base_binaries }}"

# - name: disable iptables to avoid conflicts with Docker iptables rules
#   service:
#     name: iptables
#     state: stopped
#     enabled: no
#   become: true

# - name: install ntpd
#   yum:
#     name: ntp
#     state: latest
#   become: true

# - name: start and enable ntpd
#   service:
#     name: ntpd
#     state: started
#     enabled: yes
#   become: true

# - name: install flannel (overlay network support)
#   yum:
#     name: flannel
#     state: latest
#   become: true
