---
# handlers file for wdijkerman.zabbix

- name: zabbix-server restarted
  service: name=zabbix-server state=restarted enabled=yes
  tags: zabbix-server

- name: restart apache
  service: name=httpd state=restarted enabled=yes
  tags: zabbix-server
