kube_master_hostname: "taskmngr1"
kube_master_ip: "192.168.59.2"
kubelet_package_name: "kubelet"
kubeadm_package_name: "kubeadm"
kubectl_package_name: "kubectl"
kubecni_package_name: "kubernetes-cni"
kube_base_binaries:
  - docker
  - kubelet
kube_users:
  - { name: "root", group: "root", home: "/root" }
  - { name: "{{ ansible_ssh_user }}", group: "{{ ansible_ssh_user }}", home: "/home/{{ ansible_ssh_user }}" }
# KUBECONFIG: "/home/deploy/admin.conf"
