kube_master_hostname: "taskmngr1"
kube_base_packages:
  - kubelet
  - kubeadm
  - kubectl
  - kubernetes-cni
kube_base_binaries:
  - docker
  - kubelet
kube_users:
  - { name: "root", group: "root", home: "/root" } 
  - { name: "{{ ansible_ssh_user }}", group: "{{ ansible_ssh_user }}", home: "/home/{{ ansible_ssh_user }}" }
