apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: taskmngr
  name: taskmngr
spec:
  replicas: 1
  selector:
    app: taskmngr
  template:
    metadata:
      labels:
        app: taskmngr
    spec:
      containers:
        -
          image: postgres
          name: postgres
          ports:
            -
              containerPort: 5432
        -
          image: bititanb/taskmngr
          name: django
          ports:
            -
              containerPort: 8000
        -
          image: nginx
          name: nginx
          ports:
            -
              containerPort:8000
