apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskmngr
  name: taskmngr
spec:
  ports:
    -
      name: postgres
      port: 5432
    -
      name: django
      port: 8000
    -
      name: nginx
      port: 8000
  selector:
    app: taskmngr
  type: LoadBalancer

