---

- name: reset cluster
  shell: "kubeadm reset"
  when: force_kubeadm

- name: initialize cluster with kubeadm
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16"
  register: kubeadm_init
  changed_when: kubeadm_init.rc == 0
  failed_when: kubeadm_init.rc > 0 and kubeadm_init.rc != 2

- name: copy kubeconfig file to enable kubectl
  shell: |
    cp /etc/kubernetes/admin.conf {{ item.home }}/
    chown {{ item.name }}:{{ item.group }} {{ item.home }}/admin.conf
  changed_when: false
  with_items: "{{ kube_users }}"

- name: specify path via variable to kubeconfig file to enable kubectl
  lineinfile:
    dest: "{{ item.home }}/.bash_profile"
    regexp: '^export KUBECONFIG='
    line: "export KUBECONFIG={{ item.home }}/admin.conf"
  with_items: "{{ kube_users }}"

- name: deploy flannel network in pod with kubectl
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    echo "DEBUG: KUBECONFIG=$KUBECONFIG"
  changed_when: false

- name: remember the token to use for kubeadm join on other nodes
  shell: "kubeadm token list | sed -n 2p | cut -d' ' -f1"
  register: token
  changed_when: false

- name: remember the apiserver host-port to use for kubeadm join
  shell: "kubectl -n kube-system get pods | grep kube-apiserver | cut -d' ' -f1 | xargs -I{} kubectl -n kube-system describe pod {} | grep -E '(--advertise-address|--secure-port)' | sort | cut -d'=' -f2 | tr '\n' ':' | cut -d':' -f1,2"
  register: apiserver
  until: apiserver.stdout != ""
  retries: 24
  delay: 5
  changed_when: false
