---

- name: restart kubernetes apiserver
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    "{{ kube_master_binaries }}"
  become: true

- name: restart etcd
  service:
    name: etcd
    state: restarted
  become: true

- name: restart flanneld
  service:
    name: flanneld
    state: restarted
  become: true
