- name: install docker
  yum:
    name: docker
  become: true

- name: install pip
  yum:
    name: python-pip
  become: true

- name: install docker-compose
  pip:
    name: docker-compose
  become: true
