- name: activate overlayfs
  shell: |
    echo "overlay" > /etc/modules-load.d/overlay.conf
    modprobe overlay
    mkdir -p /etc/systemd/system/docker.service.d

- name: enable overlayfs for docker systemd service
  blockinfile:
    path: /etc/systemd/system/docker.service.d/override.conf
    create: yes
    block: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/docker daemon --storage-driver=overlay

- name: install docker yum packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_yum_packages }}"

- name: install docker pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ docker_pip_packages }}"

- name: enable docker service
  service:
    name: docker
    enabled: true
    state: started
