- name: install docker yum packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_yum_packages }}"

- name: install docker pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ docker_pip_packages }}"

- name: enable docker service
  service:
    name: docker
    enabled: true
    state: started
