- name: activate overlayfs
  shell: |
    echo "overlay" > /etc/modules-load.d/overlay.conf
    modprobe overlay
    mkdir -p /etc/systemd/system/docker.service.d

- name: enable overlayfs for docker systemd service
  blockinfile:
    path: /etc/systemd/system/docker.service.d/override.conf
    create: yes
    block: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/docker daemon --storage-driver=overlay

- name: enable upstream docker repo
  blockinfile:
    path: /etc/yum.repos.d/docker.repo
    create: yes
    block: |
      [dockerrepo]
      name=Docker Repository
      baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
      enabled=1
      gpgcheck=1
      gpgkey=https://yum.dockerproject.org/gpg
  when: docker_from_upstream

- name: install docker from upstream
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_upstream_packages }}"
  when: docker_from_upstream

- name: install docker from centos official repos
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_stable_packages }}"
  when: not docker_from_upstream

- name: install docker pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ docker_pip_packages }}"

- name: enable docker service
  service:
    name: docker
    enabled: true
    state: started
