---

- name: reset kube node
  shell: "kubeadm reset"
  when: force_kubeadm

- name: get token and apiserver for kubeadm join
  include_vars: "{{ ansible_persistent_facts_file }}"
  connection: localhost

- name: join the cluster with kubeadm
  command: "kubeadm join --token {{ token }} {{ apiserver }}"
  register: join
  changed_when: join.rc == 0
  failed_when: join.rc > 0 and join.rc != 2
  retries: 3
  delay: 10

- name: wait until kubelet.conf created
  wait_for: 
    path: "/etc/kubernetes/kubelet.conf"
    state: present

- name: copy kubeconfig file to enable kubectl
  shell: |
    cp /etc/kubernetes/kubelet.conf {{ item.home }}/
    chown {{ item.name }}:{{ item.group }} {{ item.home }}/kubelet.conf
  changed_when: false
  with_items: "{{ kube_users }}"

- name: specify path via variable to kubeconfig file to enable kubectl
  lineinfile:
    dest: "{{ item.home }}/.bash_profile"
    regexp: '^export KUBECONFIG='
    line: "export KUBECONFIG={{ item.home }}/kubelet.conf"
  with_items: "{{ kube_users }}"
