---

- name: reset kube node
  shell: "kubeadm reset"
  when: force_kubeadm

- name: join the cluster with kubeadm
  command: "kubeadm join --token {{ hostvars[groups['kubernetes-master'][0]]['token']['stdout'] }} {{ hostvars[groups['kubernetes-master'][0]]['apiserver']['stdout'] }}"
  register: join
  changed_when: join.rc == 0
  failed_when: join.rc > 0 and join.rc != 2

- name: copy kubeconfig file to enable kubectl
  shell: |
    cp /etc/kubernetes/kubelet.conf {{ item.home }}/
    chown {{ item.name }}:{{ item.group }} {{ item.home }}/kubelet.conf
  changed_when: false
  with_items: "{{ kube_users }}"

- name: specify path via variable to kubeconfig file to enable kubectl
  lineinfile:
    dest: "{{ item.home }}/.bash_profile"
    regexp: '^export KUBECONFIG='
    line: "export KUBECONFIG={{ item.home }}/kubelet.conf"
  with_items: "{{ kube_users }}"
