# vim: ts=2 sw=2 et :
---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - docker-registry

# Run docker image
- name: run docker image
  docker_container:
    name: "{{ docker_registry_service_name }}"
    image: "{{ docker_registry_image }}"
    published_ports:
      - "{{ docker_registry_service_port }}:{{ docker_registry_service_port }}"
    state: "{{ docker_registry_service_status }}"
    restart_policy: "{{ docker_registry_service_restart_policy }}"
    pull: "{{ docker_registry_image_pull }}"
    volumes:
      - "{{ docker_registry_storage_path }}:{{ docker_registry_storage_volume }}"
      - "{{ docker_registry_certs_path }}:{{ docker_registry_certs_volume }}"
      - "{{ docker_registry_keys_path }}:{{ docker_registry_keys_volume }}"
    env: "{{ docker_registry_env }}"
  become: yes
  tags:
    - docker-registry
