# vim: ts=2 sw=2 et :
---
#Container image name
docker_registry_image: registry
docker_registry_image_pull: missing
docker_registry_storage_path: /var/cache/docker/registry
docker_registry_storage_volume: /var/lib/registry
docker_registry_service_name: docker_registry
docker_registry_service_status: started
docker_registry_service_restart_policy: unless-stopped
docker_registry_service_port: 5000
docker_registry_certs_path: /etc/pki/tls/certs
docker_registry_certs_volume: /certs
docker_registry_keys_path: /etc/pki/tls/private
docker_registry_keys_volume: /keys
docker_registry_hostname: 'taskmngr1'
docker_registry_env:
  REGISTRY_HTTP_TLS_CERTIFICATE: "{{ docker_registry_certs_volume }}/{{ docker_registry_hostname }}.crt"
  REGISTRY_HTTP_TLS_KEY: "{{ docker_registry_keys_volume }}/{{ docker_registry_hostname }}.key"
